### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by xarryon** [VISION-SJTU/RECCE#25]
Thx for this great work!! I wonder if you can share the link to download DFDC dataset.
I know this problem seems independent to the method. When I register the accout in https://dfdc.ai/sign-up, it always appears that "Exceeded daily email limit for the operation or the account. If a higher limit is required, please configure your user pool to use your own Amazon SES configuration for sending email." So I can't download the dataset from the offical website : (

**Comment by XJay18** [comment]
Hi, sorry for the late reply.
Unfortunately, I am not able to share the whole DFDC dataset due to its large volume and limited cloud storage I have. However, I succeeded in uploading its original validation and testing split. If you want to access these two splits of DFDC, please send me (`junyicao@sjtu.edu.cn`) an email using your academic email address.
By the way, I notice that Kaggle has provided the training part of DFDC [here](https://www.kaggle.com/competitions/deepfake-detection-challenge/data), which may be helpful to you.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
